export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCEED: "category/FETCH_CATEGORIES_SUCCEED",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",
};
